---
- hosts: all
  sudo: yes
  tasks:
  - name: install packages
    apt: name={{item}} state=latest update_cache=yes
    with_items:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'docker.io' 

